### ISSUE TITLE
Make production PR checklist reusable

### ISSUE THREAD

**Issue by jacquelynsmale** [ASFHyP3/actions#56]
Instead of copying and pasting [the release template](https://github.com/ASFHyP3/hyp3/blob/develop/.github/workflows/release-template-comment.yml), we should make a reusable version to include in our repositories.

**Comment by jhkennedy** [comment]
@jacquelynsmale there already is one!
https://github.com/ASFHyP3/actions#reusable-relese-checklist-commentyml

**Comment by jacquelynsmale** [comment]
Oh lol thanks @jhkennedy
